apiVersion: v1
kind: Service
metadata:
  name: fastapi-service-app1
  namespace: fastapi-app
spec:
  type: ClusterIP
  selector:
    app: fastapi
    service: app1
  ports:
    - port: 80
      targetPort: 80
