apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  namespace: fastapi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
        - name: app2
          image: karthianbazhagan4/fastapi-app:3b80bdd1
          ports:
            - containerPort: 80
          env:
            - name: SERVICE_NAME
              value: "app2"
