apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app2
  namespace: fastapi-app
  labels:
    app: fastapi
    service: app2
env:
  - name: SERVICE_NAME
    value: app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
      service: app2
  template:
    metadata:
      labels:
        app: fastapi
        service: app2
    spec:
      containers:
        - name: fastapi-app2
          image: karthianbazhagan4/fastapi-app:712b8769
          ports:
            - containerPort: 80
          env:
            - name: SERVICE_NAME
              value: app2
